from calc import calc1
z = calc1()
x = float(input("Digite a primeira parcela: "))
y = float(input("Digite a segunda parcela: "))
print (x,"+", y, "=", z.soma(x,y))
x = float(input("Digite o termo 1 da subtração: "))
y = float(input("Digite o temo 2 da subtração: "))
print (x,"-", y, "=", z.subtrai(x, y))
x = float(input("Digite o fator 1 da multiplicação: "))
y = float(input("Digite o fator 2 da multiplicação: "))
print (x,"x", y, "=", z.multiplica(x,y))
x = float(input("Digite o dividendo: "))
y = float(input("Digite o divisor: "))
print (x,"/", y, "=", z.divide(x,y))
